language: java
jdk: openjdk10

git:
  depth: false

addons:
  sonarcloud:
    organization: "sacontreras-github" # the key of the org you chose at step #3

#see https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle,
script:
  - ./gradlew check test --info
  - ls ./build/classes
  - sonar-scanner